# 设置语言
language: node_js

# 设置相应的版本
node_js: stable

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

# 更改时区
before_install:
  - export TZ='Asia/Shanghai'

# 安装hexo及插件
install:
  - npm install

# 下拉代码后执行的操作
script:
  - hexo clean  #清除
  - hexo g && gulp  #生成

after_script:
  # GH_REF是最下面配置的仓库地址
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  # 修改github的用户名
  - git config user.name "soldiergit"
  # 修改email
  - git config user.email "soldier_wyyx@163.com"
  - git add .
  # 提交记录包含时间 跟上面更改时区配合
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # Travis_Token是在Travis官网中配置环境变量的名称（more options 选择 setting添加的值）
  - git push --force --quiet "https://${Github_Token}@${GH_REF}" master:master

# 只监测resource分支，resource是我存放源码的分支的名称，可根据自己情况设置
branches:
  only:
    - resource

# 配置常量
env:
  global:
    # 设置GH_REF，注意更改yourname及末尾加上.git
    - GH_REF: github.com/soldiergit/soldiergit.github.io.git
    # 加密后的github token（命令：travis encrypt -r soldiergit/soldiergit.github.io GH_Token=xxxxxx）
    - secure: `eF5BarpKYOE0Y2OKcFbXLZGxD6xEVDP3RIIHDtzq07+LArju2sLoANhvJFzCev98+6828E3IAeqbrEh/kg2+7tsjCbmX0NU8lvvvyBaQ3YVk1fmVHc7vyjpB20j3FDMt11NTt43xnnSKMbmvwEOG2blis+Fvb186DRsNC6AefzVP+nul9jbVLDqp40FvXFbgEquZHGivjoVkL0ouLo2WTvtyrl/Nc63XD/AeRhqMBTiL5pg91HYZXei6tAt60ZyySSl0+qv6utipM+s68gcAprkGnwUGcrJc5PdEkys/jwjt7YDHlUy7WRcoOnXmAEzYf5o0Sxn8ztnYciYxinbCF8xJbGwpuYMWkdhREBmZKELIvND6M1rjEPttKa81UxQYwxg9g6BabEBOgx0Ozyun+XHfjMG4fAxNbgA2trUrV/Ri48VkqueJQz8EjSJtU0Yr3CL+GCV7LLsGUoR85kFEGQa6+cXH/GrCRLO42mZcMbsNSqBmZokiT9kNvYCsyPohomBDY5DYeR5JaT+c25J0GCXxMzCgPzOariqk6MPbGBlGHaghvHpG+psnD0fkeQCcF9iPxcHV5ruCAAE6DY4mRgkIYaZ41OyGTcAj1SMniGYG1SWNN3FNzwhU33Yu17iMG8XVlw0m9iMDDPcFnaHxdd5elff/TVoltPRlBcfXmYI=`

# 配置通知（电子邮件、IRC、campfire等）
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 583403411@qq.com
    - soldier_wyyx@163.com
  on_success: change
  on_failure: always
