# 设置语言
language: node_js

# 设置相应的版本
node_js: stable

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

# 更改时区
before_install:
  - export TZ='Asia/Shanghai'

# 安装hexo及插件
install:
  - npm install

# 下拉代码后执行的操作
script:
  - hexo clean # 清除
  - hexo g # 生成

after_script:
  - cd ./public
  - git init
  # 修改github的用户名
  - git config user.name "soldiergit"
  # 修改email
  - git config user.email "soldier_wyyx@163.com"
  - git add .
  # 提交记录包含时间 跟上面更改时区配合
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # Travis_Token是在Travis官网中配置环境变量的名称（more options 选择 setting添加的值）
  - git push --force --quiet "https://${Github_Token}@${GH_REF}" master:master
  # 【2021.05.13】修改gitee的用户名
  - git config user.name "${Gitee_Username}"
  # 【2021.05.13】也提交到码云
  - git push --force --quiet https://${Gitee_Username}:${Gitee_Token}@${GE_REF} master:master

# 只监测resource分支，resource是我存放源码的分支的名称，可根据自己情况设置
branches:
  only:
    - resource

# 配置常量
env:
  global:
    # 设置GH_REF，注意更改yourname及末尾加上.git
    - GH_REF: github.com/soldiergit/soldiergit.github.io.git
    # 【2021.05.13】码云的
    - GE_REF: gitee.com/soldiergitee/soldiergitee.git

# 配置通知（电子邮件、IRC、campfire等）
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 583403411@qq.com
    - soldier_wyyx@163.com
  on_success: change
  on_failure: always
